# Generated by Django 5.0.2 on 2024-02-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='link',
            field=models.TextField(blank=True, default=''),
        ),
    ]
