# Generated by Django 5.0.2 on 2024-02-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidder', '0002_property_image_data_alter_property_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image_data',
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, upload_to='property_images/'),
        ),
    ]
