# Generated by Django 5.0.2 on 2024-02-18 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidder', '0003_remove_property_image_data_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='uploaded_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date uploaded'),
        ),
    ]
