# Generated by Django 5.0.2 on 2024-02-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidder', '0004_alter_property_uploaded_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='biduser',
            name='first_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='biduser',
            name='surname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
