# Generated by Django 5.0.2 on 2024-02-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidder', '0005_biduser_first_name_biduser_surname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'permissions': [('view_bids', 'Can view all bids')]},
        ),
    ]
